//@ui5-bundle com/myorg/myapp/Component-preload.js
sap.ui.predefine("com/myorg/myapp/Component", ["sap/ui/core/UIComponent","sap/ui/Device","./model/models"],function(t,e,i){"use strict";return t.extend("com.myorg.myapp.Component",{metadata:{manifest:"json"},init:function(){t.prototype.init.call(this);this.setModel(i.createDeviceModel(),"device");this.getRouter().initialize()},getContentDensityClass:function(){if(this.contentDensityClass===undefined){if(document.body.classList.contains("sapUiSizeCozy")||document.body.classList.contains("sapUiSizeCompact")){this.contentDensityClass=""}else if(!e.support.touch){this.contentDensityClass="sapUiSizeCompact"}else{this.contentDensityClass="sapUiSizeCozy"}}return this.contentDensityClass}})});
sap.ui.predefine("com/myorg/myapp/controller/App.controller", ["./BaseController"],function(t){"use strict";return t.extend("com.myorg.myapp.controller.App",{onInit:function(){this.getView().addStyleClass(this.getOwnerComponent().getContentDensityClass())}})});
sap.ui.predefine("com/myorg/myapp/controller/BaseController", ["sap/ui/core/mvc/Controller","sap/ui/core/UIComponent","sap/ui/core/routing/History"],function(e,t,n){"use strict";return e.extend("com.myorg.myapp.controller.BaseController",{getOwnerComponent:function(){return e.prototype.getOwnerComponent.call(this)},getRouter:function(){return t.getRouterFor(this)},getResourceBundle:function(){const e=this.getOwnerComponent().getModel("i18n");return e.getResourceBundle()},getModel:function(e){return this.getView().getModel(e)},setModel:function(e,t){this.getView().setModel(e,t);return this},navTo:function(e,t,n){this.getRouter().navTo(e,t,undefined,n)},onNavBack:function(){const e=n.getInstance().getPreviousHash();if(e!==undefined){window.history.go(-1)}else{this.getRouter().navTo("main",{},undefined,true)}}})});
sap.ui.predefine("com/myorg/myapp/controller/Main.controller", ["./BaseController","sap/m/MessageBox"],function(e,o){"use strict";return e.extend("com.myorg.myapp.controller.Main",{sayHello:function(){o.show("Hello World!")}})});
sap.ui.predefine("com/myorg/myapp/model/formatter", function(){"use strict";return{formatValue:function(e){return e&&e.toUpperCase()}}});
sap.ui.predefine("com/myorg/myapp/model/models", ["sap/ui/model/json/JSONModel","sap/ui/model/BindingMode","sap/ui/Device"],function(e,n,i){"use strict";return{createDeviceModel:function(){const o=new e(i);o.setDefaultBindingMode(n.OneWay);return o}}});
sap.ui.require.preload({
	"com/myorg/myapp/i18n/i18n.properties":'appTitle=com.myorg.myapp\nappDescription=UI5 Application com.myorg.myapp\nbtnText=Say Hello\n',
	"com/myorg/myapp/i18n/i18n_de.properties":'appTitle=com.myorg.myapp\nappDescription=UI5 Application com.myorg.myapp\nbtnText=Sag Hallo\n',
	"com/myorg/myapp/i18n/i18n_en.properties":'appTitle=com.myorg.myapp\nappDescription=UI5 Application com.myorg.myapp\nbtnText=Say Hello\n',
	"com/myorg/myapp/manifest.json":'{"_version":"1.12.0","sap.app":{"id":"com.myorg.myapp","type":"application","i18n":"i18n/i18n.properties","title":"{{appTitle}}","description":"{{appDescription}}","applicationVersion":{"version":"1.0.0"}},"sap.ui":{"technology":"UI5","icons":{},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"rootView":{"viewName":"com.myorg.myapp.view.App","type":"XML","async":true,"id":"app"},"dependencies":{"minUI5Version":"1.133.0","libs":{"sap.ui.core":{},"sap.m":{},"sap.tnt":{},"sap.ui.layout":{}}},"handleValidation":true,"contentDensities":{"compact":true,"cozy":true},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","settings":{"bundleName":"com.myorg.myapp.i18n.i18n"}},"":{"type":"sap.ui.model.odata.v4.ODataModel","settings":{"serviceUrl":"/odata/airline/","synchronizationMode":"None","operationMode":"Server"}},"side":{"type":"sap.ui.model.json.JSONModel","uri":"model/sideContent.json"}},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"com.myorg.myapp.view","controlId":"mainContents","controlAggregation":"pages","async":true},"routes":[{"pattern":"","name":"main","target":"main"}],"targets":{"main":{"viewId":"main","viewName":"Main"}}}}}',
	"com/myorg/myapp/view/App.view.xml":'<mvc:View\n\tcontrollerName="com.myorg.myapp.controller.App"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n\txmlns:mvc="sap.ui.core.mvc"\n\txmlns:tnt="sap.tnt"\n\t><tnt:ToolPage\n\t\tid="app"\n\t\tclass="headerBackground"><tnt:header><tnt:ToolHeader><Button\n\t\t\t\t\tid="sideNavigationToggleButton"\n\t\t\t\t\ticon="sap-icon://menu2"\n\t\t\t\t\ttype="Transparent"\n\t\t\t\t\tpress=".onSideNavButtonPress"\n\t\t\t\t\ttooltip="{i18n>collpaseMenuButtonText}"><layoutData><OverflowToolbarLayoutData priority="NeverOverflow"/></layoutData></Button><ToolbarSpacer/><Title\n\t\t\t\t\ttext="{i18n>appTitle}"\n\t\t\t\t\tlevel="H2"/><ToolbarSpacer/><Button\n\t\t\t\t\tid="notificationButton"\n\t\t\t\t\ticon="sap-icon://ui-notifications"\n\t\t\t\t\ttype="Transparent"\n\t\t\t\t\tpress=".onNotificationPress"\n\t\t\t\t\ttooltip="{i18n>notificationButtonTooltip}"><layoutData><OverflowToolbarLayoutData closeOverflowOnInteraction="false"/></layoutData></Button><Button\n\t\t\t\t\tid="loginButton"\n\t\t\t\t\ttext="{i18n>loginButtonName}"\n\t\t\t\t\ttype="Transparent"\n\t\t\t\t\tpress=".onLoginPress"\n\t\t\t\t\ttooltip="{i18n>loginButtonTooltip}"><layoutData><OverflowToolbarLayoutData closeOverflowOnInteraction="false"/></layoutData></Button><Avatar\n\t\t\t\t\t\t\tid="avatarButton"\n\t\t\t\t\t\t\tinitials="VB"\n\t\t\t\t\t\t\tvisible="false"\n\t\t\t\t\t\t\tsrc="./images/vb.jpg"\n\t\t\t\t\t\t\tdisplaySize="XS"\n\t\t\t\t\t\t\tshowBorder="true"\n\t\t\t\t\t\t\tpress=".onLoginPress"/></tnt:ToolHeader></tnt:header><tnt:sideContent><tnt:SideNavigation\n\t\t\t\texpanded="false"\n\t\t\t\tid="sideNavigation"\n\t\t\t\tselectedKey="{side>/selectedKey}"><tnt:NavigationList\n\t\t\t\t\titems="{\n\t\t\t\t\t\tpath: \'side>/navigation\',\n\t\t\t\t\t\ttemplateShareable: false\n\t\t\t\t\t}"><tnt:NavigationListItem\n\t\t\t\t\t\ttext="{path: \'side>titleI18nKey\'}"\n\t\t\t\t\t\ticon="{side>icon}"\n\t\t\t\t\t\texpanded="{side>expanded}"\n\t\t\t\t\t\titems="{\n\t\t\t\t\t\t\tpath: \'side>items\',\n\t\t\t\t\t\t\ttemplateShareable: false\n\t\t\t\t\t\t}"\n\t\t\t\t\t\tkey="{side>key}"\n\t\t\t\t\t\thref="#/{side>key}"><tnt:NavigationListItem\n\t\t\t\t\t\t\ttext="{path: \'side>titleI18nKey\'}"\n\t\t\t\t\t\t\tkey="{side>key}"\n\t\t\t\t\t\t\thref="#/{side>key}"></tnt:NavigationListItem></tnt:NavigationListItem></tnt:NavigationList><tnt:fixedItem><tnt:NavigationList\n\t\t\t\t\t\titems="{\n\t\t\t\t\t\t\tpath: \'side>/fixedNavigation\',\n\t\t\t\t\t\t\ttemplateShareable: false\n\t\t\t\t\t\t}"><tnt:NavigationListItem\n\t\t\t\t\t\t\ttext="{path: \'side>titleI18nKey\'}"\n\t\t\t\t\t\t\ticon="{side>icon}"\n\t\t\t\t\t\t\tkey="{side>key}"\n\t\t\t\t\t\t\thref="#/{side>key}"></tnt:NavigationListItem></tnt:NavigationList></tnt:fixedItem></tnt:SideNavigation></tnt:sideContent><tnt:mainContents><App id="mainContents"/></tnt:mainContents></tnt:ToolPage></mvc:View>\n',
	"com/myorg/myapp/view/Main.view.xml":'<mvc:View\n\tcontrollerName="com.myorg.myapp.controller.Main"\n\tdisplayBlock="true"\n\txmlns="sap.m"\n    xmlns:mvc="sap.ui.core.mvc"\n\txmlns:core="sap.ui.core"\n\t\n\tcore:require="{\n\t\tformatter: \'com/myorg/myapp/model/formatter\'\n\t}"><Page\n\t\ttitle="Bella Beludas"\n\t\tid="page"><content><Table\n                id="passageiroTable"\n                items="{/Passageiro}"\n                growing="true"\n                growingMode="Scroll"\n                inset="false"\n                width="100%"><headerToolbar><Toolbar><Title text="Lista de Passageiros"/></Toolbar></headerToolbar><columns><Column><Text text="ID"/></Column><Column><Text text="Nome"/></Column><Column><Text text="CPF"/></Column></columns><items><ColumnListItem><cells><Text text="{id_passageiro}" /><Text text="{nome}" /><Text text="{cpf}" /></cells></ColumnListItem></items></Table></content></Page></mvc:View>\n'
});
//# sourceMappingURL=Component-preload.js.map
